# Generated by Django 4.2.1 on 2023-05-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('puertas', models.CharField(max_length=100)),
                ('tipo_carroceria', models.CharField(max_length=100)),
                ('anyo', models.CharField(max_length=100)),
                ('tipo_motor', models.CharField(max_length=100)),
                ('caballos', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
