# Generated by Django 4.2.1 on 2023-05-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('1', 'Rojo'), ('3', 'Verde'), ('8', 'Granate'), ('2', 'Azul'), ('7', 'Plata'), ('5', 'Negro'), ('0', 'Blanco'), ('6', 'Gris'), ('9', 'Turquesa'), ('4', 'Amarillo'), ('10', 'Naranja')], max_length=100)),
                ('puertas', models.CharField(choices=[('0', 'Tres'), ('2', 'Cinco'), ('1', 'Cuatro')], max_length=100)),
                ('tipo_carroceria', models.CharField(max_length=100)),
                ('anyo', models.CharField(max_length=100)),
                ('tipo_motor', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('rol', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('coche_propiedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Vehicar_Rentals.coche')),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_alquiler', models.DateField(max_length=100)),
                ('fecha_fin_alquiler', models.DateField(max_length=100)),
                ('precio_alquiler', models.IntegerField()),
                ('coche_alquilado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Vehicar_Rentals.coche')),
                ('email_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Vehicar_Rentals.persona')),
            ],
        ),
    ]
