# Generated by Django 4.2.1 on 2023-05-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicar_Rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='color',
            field=models.CharField(choices=[('8', 'Granate'), ('9', 'Turquesa'), ('1', 'Rojo'), ('0', 'Blanco'), ('2', 'Azul'), ('3', 'Verde'), ('4', 'Amarillo'), ('10', 'Naranja'), ('7', 'Plata'), ('6', 'Gris'), ('5', 'Negro')], max_length=100),
        ),
    ]
