# Generated by Django 4.2.1 on 2023-05-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicar_Rentals', '0002_alter_coche_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='caballos',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coche',
            name='color',
            field=models.CharField(choices=[('0', 'Blanco'), ('6', 'Gris'), ('1', 'Rojo'), ('4', 'Amarillo'), ('9', 'Turquesa'), ('2', 'Azul'), ('7', 'Plata'), ('3', 'Verde'), ('10', 'Naranja'), ('5', 'Negro'), ('8', 'Granate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='coche',
            name='puertas',
            field=models.CharField(choices=[('1', 'Cuatro'), ('0', 'Tres'), ('2', 'Cinco')], max_length=100),
        ),
    ]
