# Generated by Django 4.2.1 on 2023-05-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicar_Rentals', '0003_coche_caballos_alter_coche_color_alter_coche_puertas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coche',
            name='puertas',
            field=models.CharField(max_length=100),
        ),
    ]
