# Generated by Django 3.0 on 2023-05-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coches', '0002_auto_20230502_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='color',
            field=models.CharField(choices=[('6', 'Gris'), ('8', 'Granate'), ('4', 'Amarillo'), ('1', 'Rojo'), ('2', 'Azul'), ('0', 'Blanco'), ('10', 'Naranja'), ('7', 'Plata'), ('5', 'Negro'), ('3', 'Verde'), ('9', 'Turquesa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='coche',
            name='puertas',
            field=models.CharField(choices=[('1', 'Cuatro'), ('2', 'Cinco'), ('0', 'Tres')], max_length=100),
        ),
    ]
