# Generated by Django 3.0 on 2023-05-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coches', '0003_auto_20230502_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='matricula',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coche',
            name='color',
            field=models.CharField(choices=[('2', 'Azul'), ('4', 'Amarillo'), ('3', 'Verde'), ('5', 'Negro'), ('7', 'Plata'), ('6', 'Gris'), ('1', 'Rojo'), ('0', 'Blanco'), ('8', 'Granate'), ('10', 'Naranja'), ('9', 'Turquesa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='coche',
            name='puertas',
            field=models.CharField(choices=[('0', 'Tres'), ('2', 'Cinco'), ('1', 'Cuatro')], max_length=100),
        ),
    ]
