# Generated by Django 4.2.1 on 2023-05-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_coche_propiedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='precio_alquiler',
            field=models.CharField(default=10, max_length=1000),
        ),
    ]
